### ISSUE TITLE
Runtime production crash DuplicateTaskCompletionException

### ISSUE THREAD

**Issue by AndrewMorsillo** [notifee/react-native-notifee#142]
I just deployed Notifee to our production app and it's crashing at runtime with the following exception:

```
com.google.android.gms.tasks.DuplicateTaskCompletionException: Complete with: result Done
```

Notifee is the only library in the project using play-services-tasks. We're only using local timestamp triggered notification like so:

```
const trigger: TimestampTrigger = {
            type: TriggerType.TIMESTAMP,
            timestamp: time.getTime(),
        }

        // Create a trigger notification
        await notifee.createTriggerNotification(
            {
                id,
                title,
                body: message,
                data,
                android: {
                    channelId: "default",
                    smallIcon: "@drawable/ic_notification",
                    largeIcon: "@mipmap/ic_launcher",
                    color: "#f12317",
                    pressAction: {
                        id: "default",
                        launchActivity: "default",
                    },
                },
            },
            trigger
        )
```

This seems to be affecting a large percentage of users across all device models and android versions.

**Comment by mikehardy** [comment]
I'd love to see a full stack trace if you have one? And obviously a reproduction would be great, but either way we'll start looking and any information you can share would accelerate it.

**Comment by AndrewMorsillo** [comment]
Unfortunately I don't have much to go on so far, I've only caught the error with a production crash reporting service. This stack doesn't give much to go on:

```

0 | com.google.android.gms.tasks.zzu.zzc | com.google.android.gms:play-services-tasks@@17.1.0:142
1 | com.google.android.gms.tasks.zzu.zza | com.google.android.gms:play-services-tasks@@17.1.0:116
2 | com.google.android.gms.tasks.zzy.run | com.google.android.gms:play-services-tasks@@17.1.0:5
3 | java.util.concurrent.ThreadPoolExecutor.processTask | ThreadPoolExecutor.java:1187
4 | java.util.concurrent.ThreadPoolExecutor.runWorker | ThreadPoolExecutor.java:1152
5 | java.util.concurrent.ThreadPoolExecutor$Worker.run | ThreadPoolExecutor.java:641
6 | java.lang.Thread.run | Thread.java:929

```



Here are my app dependencies, not sure if they may help narrow down the possibilities

```
"@notifee/react-native": "^0.12.2",
        "@react-native-community/async-storage": "^1.12.0",
        "@react-native-community/clipboard": "^1.2.3",
        "@react-native-community/google-signin": "^4.0.3",
        "@react-native-community/netinfo": "^5.9.5",
        "@react-native-firebase/analytics": "^7.6.1",
        "@react-native-firebase/app": "^8.4.1",
        "@react-native-firebase/auth": "^9.1.2",
        "@react-native-firebase/crashlytics": "^8.4.2",
        "@react-native-firebase/firestore": "^7.7.0",
        "@react-native-firebase/functions": "^7.4.2",
        "@react-native-firebase/messaging": "^7.8.4",
        "@react-native-firebase/perf": "^7.4.2",
        "clevertap-react-native": "^0.4.5",
        "date-fns": "^2.15.0",
        "fast-safe-stringify": "^2.0.7",
        "instabug-reactnative": "^9.1.7",
        "lodash": "^4.17.20",
        "metro-minify-terser": "^0.63.0",
        "mobx": "^5.15.4",
        "mobx-react": "^6.2.5",
        "mobx-state-tree": "^3.17.2",
        "mobx-utils": "^5.6.1",
        "moment": "^2.27.0",
        "observable-hooks": "^3.1.0",
        "react": "16.13.1",
        "react-native": "0.63.2",
        "react-native-animatable": "^1.3.3",
        "react-native-branch": "^4.4.0",
        "react-native-code-push": "^6.3.0",
        "react-native-exception-handler": "^2.10.8",
        "react-native-fbsdk": "^1.1.2",
        "react-native-popover-view": "^3.0.3",
        "react-native-restart": "^0.0.17",
        "react-native-safe-area-context": "^3.1.6",
        "react-native-sound": "^0.11.0",
        "react-native-svg": "^12.1.0",
        "react-native-vector-icons": "^7.0.0",
        "react-native-version-number": "^0.3.6",
        "react-native-xyz-scrollview": "github:AndrewMorsillo/react-native-directed-scrollview#master",
        "rxjs": "^6.6.2",
        "seedrandom": "^3.0.5",
        "smartlook-react-native-wrapper": "^0.32.0",
        "tinycolor2": "^1.4.1"
```

I'm also seeing this stack in my Android logs but I'm not sure if it's related or coming from Notifee at all. It doesn't crash the app when it happens. I'll paste it here in case it might help you narrow things down.
```
2020-09-03 22:49:45.686 1851-1894/com.whetware.taskhero W/ConnectionTracker: Exception thrown while unbinding
    java.lang.IllegalArgumentException: Service not registered: com.google.android.gms.measurement.internal.zzjn@bf11e56
        at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1757)
        at android.app.ContextImpl.unbindService(ContextImpl.java:1874)
        at android.content.ContextWrapper.unbindService(ContextWrapper.java:792)
        at com.google.android.gms.common.stats.ConnectionTracker.zza(com.google.android.gms:play-services-basement@@17.3.0:55)
        at com.google.android.gms.common.stats.ConnectionTracker.unbindService(com.google.android.gms:play-services-basement@@17.3.0:50)
        at com.google.android.gms.measurement.internal.zzis.zzah(com.google.android.gms:play-services-measurement-impl@@17.4.4:251)
        at com.google.android.gms.measurement.internal.zzis.zzam(com.google.android.gms:play-services-measurement-impl@@17.4.4:268)
        at com.google.android.gms.measurement.internal.zzis.zzc(com.google.android.gms:play-services-measurement-impl@@17.4.4:335)
        at com.google.android.gms.measurement.internal.zziv.zza(com.google.android.gms:play-services-measurement-impl@@17.4.4:2)
        at com.google.android.gms.measurement.internal.zzaj.run(com.google.android.gms:play-services-measurement-impl@@17.4.4:7)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.google.android.gms.measurement.internal.zzga.run(com.google.android.gms:play-services-measurement-impl@@17.4.4:21)
```

**Comment by AndrewMorsillo** [comment]
Another possibly related stack trace but I've only seen this one once
```
data:text/text;charset=utf-8,
java.util.concurrent.RejectedExecutionException: Task com.google.android.gms.tasks.zzj@e6b2af8 rejected from java.util.concurrent.ThreadPoolExecutor@e890bd1[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
	 at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2086)
	 at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:848)
	 at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1394)
	 at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:630)
	 at com.google.android.gms.tasks.zzi.zza(com.google.android.gms:play-services-tasks@@17.1.0:10)
	 at com.google.android.gms.tasks.zzq.zza(com.google.android.gms:play-services-tasks@@17.1.0:19)
	 at com.google.android.gms.tasks.zzu.zza(com.google.android.gms:play-services-tasks@@17.1.0:104)
	 at com.google.android.gms.tasks.zzd.onSuccess(com.google.android.gms:play-services-tasks@@17.1.0:8)
	 at com.google.android.gms.tasks.zzn.run(com.google.android.gms:play-services-tasks@@17.1.0:4)
	 at com.google.android.gms.tasks.zzt.execute(com.google.android.gms:play-services-tasks@@17.1.0:2)
	 at com.google.android.gms.tasks.zzm.zza(com.google.android.gms:play-services-tasks@@17.1.0:11)
	 at com.google.android.gms.tasks.zzq.zza(com.google.android.gms:play-services-tasks@@17.1.0:19)
	 at com.google.android.gms.tasks.zzu.zze(com.google.android.gms:play-services-tasks@@17.1.0:151)
	 at com.google.android.gms.tasks.zzu.addOnSuccessListener(com.google.android.gms:play-services-tasks@@17.1.0:34)
	 at com.google.android.gms.tasks.zzf.run(com.google.android.gms:play-services-tasks@@17.1.0:15)
	 at android.os.Handler.handleCallback(Handler.java:883)
	 at android.os.Handler.dispatchMessage(Handler.java:100)
	 at com.google.android.gms.internal.tasks.zzb.dispatchMessage(com.google.android.gms:play-services-tasks@@17.1.0:6)
	 at android.os.Looper.loop(Looper.java:214)
	 at android.app.ActivityThread.main(ActivityThread.java:7356)
	 at java.lang.reflect.Method.invoke(Native Method)
	 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)


```

**Comment by mikehardy** [comment]
I have dug into a related issue on that last stack, when you see this:

> java.util.concurrent.ThreadPoolExecutor@e890bd1[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]

That means the pool is on the way down and is draining, typically due to some other thread blowing up and tearing the whole thing down, then as the app is going down a thread that was still waiting for completion does something and the ThreadPoolExecutor basically says "nope, we're shutting down, sorry"

**Comment by AndrewMorsillo** [comment]
Makes sense. I've only seen that stack reported once so it's probably just a fluke. The first stack in the original report however `DuplicateTaskCompletionException ` is happening to a lot of users on a lot of different devices and Android versions.

**Comment by AndrewMorsillo** [comment]
Another clue, the last log line captured before the exception indicates that `createTriggerNotification` was likely the call that resulted in the exception

This `onForegroundEvent` handler runs as one of the very last logs printed _after_ the exception. Is it possible that notifee is crashing if you `createTriggerNotification` with an `id` that already exists?

```
"type":7,"detail":{"notification":{"title":"Your Activity Charges are ready!","data":{},"id":"microhabit_1","body":"Time to make quick progress!","android":{"importance":3,"groupSummary":false,"colorized":false,"visibility":0,"pressAction":{"launchActivity":"default","id":"default"},"smallIcon":"@drawable/ic_notification","color":"#f12317","asForegroundService":false,"ongoing":false,"showTimestamp":false,"badgeIconType":2,"onlyAlertOnce":false,"groupAlertBehavior":0,"showChronometer":false,"channelId":"default","autoCancel":true,"largeIcon":"@mipmap/ic_launcher","localOnly":false,"defaults":[-1],"chronometerDirection":"up"},"subtitle":""}}
```

**Comment by AndrewMorsillo** [comment]
@mikehardy I just noticed this happen while an update was being applied from Appcenter Codepush. This exception was thrown and the update failed on the device. Perhaps the cause of this issue is an interaction between react-native-codepush and Notifee?

**Comment by mikehardy** [comment]
Mmm - perhaps, I looked deeply into codepush and it's on my personal / work project roadmap but I have not personally integrated or used it yet.

I believe codepush completely reinitializes the bundle though, during the same session of "native state" (which leads to problems e.g. in react-native-firebase with duplicate deep link even triggering etc) so that's the sort of thing that might cause "duplicate" type native errors.

Do I have any sort of code path to demonstrate or refute or even mark suspicious/likely this hypothesis though? I do not, sorry - I wish I did! Very interesting hypothesis though, bears investigating

Could you attest that this happens only with codepush bundle reloads? Are you able to reproduce it?

**Comment by AndrewMorsillo** [comment]
I unfortunately have not been able to reliably reproduce this yet and am not certain it's constrained to only this situation. This is the only time I've seen it happen personally, all others are just reports in crashlytics. I'll let you know if I come up with anything however.

**Comment by AndrewMorsillo** [comment]
I've captured another stack trace through crashlytics that seems like it could be related

```

Fatal Exception: java.lang.RuntimeException
Unable to start service app.notifee.core.ReceiverService@c03109c with null: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getAction()' on a null object reference
android.app.ActivityThread.handleServiceArgs (ActivityThread.java:3719)
android.app.ActivityThread.-wrap21
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1815)
android.os.Handler.dispatchMessage (Handler.java:105)
android.os.Looper.loop (Looper.java:164)
android.app.ActivityThread.main (ActivityThread.java:6797)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:240)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:772)
```

```
Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'java.lang.String android.content.Intent.getAction()' on a null object reference
app.notifee.core.ReceiverService.onStartCommand (SourceFile:1)
android.app.ActivityThread.handleServiceArgs (ActivityThread.java:3702)
android.app.ActivityThread.-wrap21
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1815)
android.os.Handler.dispatchMessage (Handler.java:105)
android.os.Looper.loop (Looper.java:164)
android.app.ActivityThread.main (ActivityThread.java:6797)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:240)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:772)
```

**Comment by mikehardy** [comment]
I doubt that is related at all unfortunately, that looks like an argument-handling safety issue on clicks where the Intent (an Android object containing the "click" or "tap" information that Android system passes to your app) isn't handled safely with regard to expectations on what should or should not be in it. I suppose it could cause a ThreadPool to be shutting down while some tasks are still lodged and cascade to the other stack so this could in effect be the root cause, but they're all more in a web of "hmmm :thinking: " vs being obviously related

**Comment by mikehardy** [comment]
@AndrewMorsillo what version did that last stack come off of? 0.12.3 (current release) or something different?

**Comment by AndrewMorsillo** [comment]
It was 0.12.3

**Comment by AndrewMorsillo** [comment]
@mikehardy I finally got this one to trigger while testing. It happened when appcenter codepush applied an update while the app was running. Hopefully that gives you a good place to look for the cause. I don't know exactly how codepush does its magic but I'd guess that there's a conflict with notifee when codepush applies a new js bundle and restarts the app.

**Comment by mikehardy** [comment]
Interesting! This means maybe we need to check for rn bridge validity when using tasks or perhaps a different usage pattern for codepush update apply would also work? Either way finally having a repro direction is nice

**Comment by sparebytes** [comment]
Is there a way to mitigate this problem? I'd love to use Notifee but can't afford to have issues with Appcenter Codepush.

**Comment by mikehardy** [comment]
@helenaford a related crash came up in react-native-firebase yesterday, it was visible on hot-reload but I think the react-native-code-push path is similar (assumption: both cause CatalystInstance - the react-native javascript layer - to be thrown away, before being completely created again).

In react-native-firebase [we hook `onCatalystDestroy` to do some cleanup](https://github.com/invertase/react-native-firebase/blob/99f8d2c912d9fe63fc6243bc0b5d43b6813a2fe5/packages/app/android/src/reactnative/java/io/invertase/firebase/common/ReactNativeFirebaseModule.java#L90-L93), and there was an issue where that threw an exception due to some new feature there related to TaskExecutors (which WorkManager here also uses under the covers)

The solution here *may* be to hook onCatalystDestroy in the notifee react-native module, then in the execution of the hook clean up the WorkManager etc. so that when the new (post-code-push update) CatalystInstance comes in to being and re-instantiates things, there are not duplicate tasks?

ref: https://github.com/invertase/react-native-firebase/issues/5225

**Comment by helenaford** [comment]
I'm failing to recreate this scenario, @AndrewMorsillo when you managed to trigger this issue, what notifee functions were you calling? 

From doing more research around `DuplicateTaskCompletionException`, three was one issue tracked https://issuetracker.google.com/issues/70416429.  Before this exception type was introduced, it looks like it used to throw `java.lang.IllegalStateException: Results have already been set `.

I'm not 100% sure how this can be related to `createTriggerNotification` but perhaps when the trigger notification is being displayed. The initial thing we can do is wrap the function where the trigger notification is handled in a try/catch. But, it would be good to know more about when this is occurring in production environment. 

@AndrewMorsillo do you have any more logs around `DuplicateTaskCompletionException`? 

Seems to be a race condition somewhere which makes this really hard to knuckle down. 

Thank you so much for what you've shared so far, and helping us troubleshoot this.

**Comment by AndrewMorsillo** [comment]
I can't pin it down to a specific notifee function unfortunately. We're using `createTriggerNotification` `cancelNotification` `createChannel` `onBackgroundEvent` and `onForegroundEvent`.  I don't have any more information about the crash right now. The only times I have seen the crash happen myself is when a codepush update is applied so @mikehardy might be on the right track there.
