### ISSUE TITLE
NullPointerException originating from BlockStateBroadcastReceiver

### ISSUE THREAD

**Issue by Maddoc42** [notifee/react-native-notifee#237]
Hey guys,

Google Play is reporting a fair number (> 2K) of NPEs with the following strack trace

```java.lang.RuntimeException: 
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:3855)
  at android.app.ActivityThread.access$1500 (ActivityThread.java:224)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1898)
  at android.os.Handler.dispatchMessage (Handler.java:107)
  at android.os.Looper.loop (Looper.java:224)
  at android.app.ActivityThread.main (ActivityThread.java:7562)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:539)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:950)
Caused by: java.lang.NullPointerException: 
  at n.o.t.i.f.e.e.nZ_i.nz_t (nZ_i.java:2)
  at app.notifee.core.BlockStateBroadcastReceiver.onReceive (BlockStateBroadcastReceiver.java:10)
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:3846)
  at android.app.ActivityThread.access$1500 (ActivityThread.java:224)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1898)
  at android.os.Handler.dispatchMessage (Handler.java:107)
  at android.os.Looper.loop (Looper.java:224)
  at android.app.ActivityThread.main (ActivityThread.java:7562)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:539)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:950)
```

The crashes are limited to Android version 9 and 10 and happen primarily on (Xiaomi) Redmi devices although there are a few other brands mixed in as well (Samsung, Motorola, ...).

Versions being used:
- notifee 1.0.0
- react native 0.63.4

Is there any way we can look deep into this what's going on? Any pointer would be much appreciated!

Thank you and thanks for creating this!

**Comment by helenaford** [comment]
Hey, sorry you're experiencing this. Thanks for sharing the crash report, it looks like it could be happening either on an incoming message or on an action press... Do you have more information on what type of notifications your displaying? Are you using trigger notifications?

**Comment by Maddoc42** [comment]
Hey @helenaford, thanks for getting back so quickly! 😊 

Please excuse if I'm not using the proper terminology, we're using the following notification types

- Trigger notifications: they are cancelled and recreated fairly frequently, at least during every app start. Notifications are scheduled a few days into the future.
- Data only and message + data notifications received from firebase and forwarded to notifee

How we used trigger notifications:

```javascript
export const scheduleNotification = (id: string, date: Date, title: string, message: string, data: ?any) =>
  async () => {
    await notifee.createChannel({
      id: CHANNEL_ID,
      name: 'TODO',
    });
    notifee.createTriggerNotification(
      {
        id,
        title,
        body: message,
        data,
        android: {
          channelId: CHANNEL_ID,
          smallIcon: 'ic_notification',
        },
      },
      {
        type: TriggerType.TIMESTAMP,
        timestamp: date.getTime(),
      }
    );
  };


export const cancelScheduledNotification = (id: string) =>
  async () => {
    await notifee.cancelNotification(id);
  };

const calledEveryStartupPlusMainContainerMount () => {
  async (dispatch: any) => {
    await dispatch(cancelScheduledNotification(ID_1));
    await dispatch(cancelScheduledNotification(ID_2));

    dispatch(scheduleNotification(
      ID_1,
      moment().add(X_SMALL, 'hours').toDate(),
      TITLE,
      MSG,
      { action: ACTION },
    ));
    dispatch(scheduleNotification(
      ID_2,
      moment().add(X_BIG, 'hours').toDate(),
      TITLE,
      MSG,
      { action: ACTION },
    ));
   }
}
```

Does this help? Thanks again!

**Comment by helenaford** [comment]
Thanks, from looking deeper, it looks like it could be happening when these events have taken place:
https://notifee.app/react-native/reference/eventtype#app_blocked
https://notifee.app/react-native/reference/eventtype#channel_blocked
https://notifee.app/react-native/reference/eventtype#channel_group_blocked

Will raise it as a bug. Do you have functionality inside the app around channels or channel groups? Or, it could be that the user has gone into their application settings and toggled them.

**Comment by Maddoc42** [comment]
> Do you have functionality inside the app around channels or channel groups?
Not to my knowledge, no. The channel in the above sample code has a static ID, so the same channel is being used for all notifications. From the backend we sometimes send notifications with a `tag`. Thanks for looking into this.

**Comment by helenaford** [comment]
Hi, so we've been looking into this and it's still a little puzzling to us because it looks like a race condition going on somewhere which makes it very hard to replicate and test. 

We've included a potential fix in the latest release (v1.1.1). Please could you try it out, and let us know if that eliminates the error. If it doesn't, we can look into another solution. 

Also, question about the devices this is occurring on, when you say it's limited to Android version 9 and 10, do you have some stats around this. Is it more 10 over 9 or vice versa or are the chances of this error occurring for either version fairly similar?  

Thanks, and again, sorry you are seeing this issue.

**Comment by Maddoc42** [comment]
Hey, bit thank you for the update! We'll try version 1.1.1 in production.

The crash happens on roughly 60% Android 10 and 40% on Android 9, so rather similar.

**Comment by helenaford** [comment]
OK, thanks! Good to know, yeah they're fairly similar.

And, no problem at all. We appreciate this is something in notifee that needs fixing, so thanks for helping us with it!

**Comment by Maddoc42** [comment]
It seems the new version fixed the previous crash and has now instead replaced it with the following:

```
java.lang.RuntimeException: 
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:3459)
  at android.app.ActivityThread.access$1300 (ActivityThread.java:201)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1690)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:201)
  at android.app.ActivityThread.main (ActivityThread.java:6864)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:547)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:873)
Caused by: java.lang.IllegalStateException: 
  at androidx.work.impl.WorkManagerImpl.getInstance (WorkManagerImpl.java:150)
  at androidx.work.WorkManager.getInstance (WorkManager.java:184)
  at app.notifee.core.BlockStateBroadcastReceiver.onReceive (BlockStateBroadcastReceiver.java:80)
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:3450)
  at android.app.ActivityThread.access$1300 (ActivityThread.java:201)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1690)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:201)
  at android.app.ActivityThread.main (ActivityThread.java:6864)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:547)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:873)
  ```
  
Distribution is roughly 70% Android 10 and 30% Android 9. We don't yet have any good numbers to see if any one particular brand / device is affected.
  
Does this seem plausible?

**Comment by mikehardy** [comment]
Plausible certainly but strange! 

- Is there any more information about the IllegalStateException, the docs indicate that there may be a message with more info
- Can you specify exactly what version you are on? That line number does not correspond to the code stack for some reason

@helenaford that API usage is not wrapped in a try/catch though it is documented to throw this exception - https://developer.android.com/reference/androidx/work/WorkManager#getInstance(android.content.Context)

> IllegalStateException | If WorkManager is not initialized properly


*Why* isn't it initialized property? Why only Android 9/10? Unknown.

I believe this is the correct version of the source and the line that threw https://android.googlesource.com/platform/frameworks/support/+/60ae0eec2a32396c22ad92502cde952c80d514a0/work/workmanager/src/main/java/androidx/work/impl/WorkManagerImpl.java#150

**Comment by helenaford** [comment]
Thanks @Maddoc42 for the new logs and sorry again for the issue. It definitely has got further! Reached nearer the end of the method, where it sends out the event. 

@mikehardy thanks for deep diving into that, will wrap it in a try and catch, hopefully that does the trick!

Very strange though that it's mainly Android 10. I'm determined to try and recreate this locally.

**Comment by mikehardy** [comment]
more than just the try/catch would be very interesting to know how the initialization could have failed. What parts of initialization have been done / have not been done.... Appears to be a few reasons and if anything could be logged about the state it might be instructive. Without the WorkManager working, the notifications have a chance of unreliability yes? Not sure how to then get that information if it only happens in the wild, we don't have analytics in the library of course, and we could emit log messages but we'd need library consumer cooperation to then look for those and post them up somehow as non-fatal messages

**Comment by Maddoc42** [comment]
The version used should be **1.1.1**.

Google Play is tracking a "separate" crash with a very similar stack trace and more info. My mistake for not revealing this sooner.

```
java.lang.RuntimeException: 
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:4111)
  at android.app.ActivityThread.access$1700 (ActivityThread.java:242)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2078)
  at android.os.Handler.dispatchMessage (Handler.java:107)
  at android.os.Looper.loop (Looper.java:237)
  at android.app.ActivityThread.main (ActivityThread.java:7830)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:492)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1040)
Caused by: java.lang.IllegalStateException: 	at androidx.work.impl.WorkManagerImpl.getInstance(WorkManagerImpl.java:150)
	at androidx.work.WorkManager.getInstance(WorkManager.java:184)
	at app.notifee.core.BlockStateBroadcastReceiver.onReceive(SourceFile:80)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4095)
	... 8 more

CPU usage from 16819ms to 4268ms ago (2021-03-19 00:31:45.988 to 2021-03-19 00:32:01.126) with 82% awake:
  18% 1452/system_server: 11% user + 6.5% kernel / faults: 7382 minor
  12% 24346/com.android.vending: 10% user + 2.3% kernel / faults: 3010 minor
  10% 24877/com.android.vending:download_service: 6% user + 4.1% kernel / faults: 1085 minor
  6.9% 786/installd: 0.5% user + 6.3% kernel / faults: 462 minor
  3.9% 25505/com.sega.score: 3.5% user + 0.3% kernel
  3.7% 458/android.system.suspend@1.0-service: 0% user + 3.7% kernel
  1.6% 294/exe_cq/0: 0% user + 1.6% kernel
  1% 20990/hif_thread: 0% user + 1% kernel
  1.4% 17914/com.android.systemui: 0.8% user + 0.5% kernel / faults: 74 minor
  1.2% 666/surfaceflinger: 0.3% user + 0.8% kernel
  0.8% 20991/rx_thread: 0% user + 0.8% kernel
  1% 9809/com.google.android.gms.persistent: 0.5% user + 0.4% kernel / faults: 132 minor
  0.8% 20989/tx_thread: 0% user + 0.8% kernel
  0.7% 295/mmcqd/0: 0% user + 0.7% kernel
  0.6% 364/logd: 0.3% user + 0.3% kernel / faults: 4 minor
  0.6% 23365/com.facebook.orca: 0.4% user + 0.1% kernel / faults: 34 minor
  0.5% 349/ueventd: 0.4% user + 0% kernel
  0.4% 8392/com.vng.inputmethod.labankey: 0.2% user + 0.2% kernel
  0.3% 850/android.hardware.sensors@2.0-service-mediatek: 0% user + 0.3% kernel
  0.3% 25956/kworker/u16:1: 0% user + 0.3% kernel
  0.3% 104/dlpt_notify_thr: 0% user + 0.3% kernel
  0.3% 394/jbd2/mmcblk0p42: 0% user + 0.3% kernel
  0.3% 599/netd: 0% user + 0.2% kernel / faults: 77 minor
  0.3% 1973/com.android.phone: 0.1% user + 0.1% kernel / faults: 44 minor
  0.2% 26170/com.zing.zalo: 0.1% user + 0.1% kernel / faults: 30 minor
  0.2% 284/ipi_cpu_dvfs_rt: 0% user + 0.2% kernel
  0.2% 664/lmkd: 0% user + 0.2% kernel
  0.2% 1334/mtkfusionrild: 0% user + 0.2% kernel
  0.2% 7314/kworker/u16:4: 0% user + 0.2% kernel
  0.1% 8/rcu_preempt: 0% user + 0.1% kernel
  0.1% 182/pbm: 0% user + 0.1% kernel
  0.1% 215/chre_kthread: 0% user + 0.1% kernel
  0.1% 655/ashmemd: 0% user + 0% kerne
```

Distribution between Android 10 and 9 is 64% to 36%. Also Google Play is stating that fewer people (roughly 50%) are affected by this exception compared to the one from earlier / above.

**Comment by helenaford** [comment]
Internal p/r going through review, will keep you updated. It should be in the next release.

**Comment by helenaford** [comment]
Latest release (1.3.1) contains a fix for `IllegalStateException` thrown by the WorkManager. Hopefully there's no more fatal exception issues. We're catching the error and logging it. If you are tracking for error logs,  it will be interesting to see if more details appear but we will be tracking this also internally ourselves. 

From reading more about this over on google issuetracker,  it happens for a small number of devices dependant on the device manufacture. Do you have any information on what devices/brands this issue occurs on? Although, I know you said previously you don't yet have any good numbers. Again, appreciate your patience and sticking in there with us.
