### ISSUE TITLE
Crashes on Android < 5.0 / API21 via transitive okhttp version

### ISSUE THREAD

**Issue by mikehardy** [notifee/react-native-notifee#95]
OkHTTP 4.x may not be used for your full API skew, if you support Android API16+ you have to use an older okhttp branch:

https://github.com/square/okhttp#requirements

OkHTTP 3.12.x branch is the requirement until API21+, with 3.12.12 current

I'll test a local switch to this and post a PR if it works

Current result of booting is 

```
06-30 21:11:04.884 17606-17606/com.kullki.kscore.dev E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.kullki.kscore.dev, PID: 17606
    java.lang.ExceptionInInitializerError
        at okhttp3.internal.platform.Android10Platform.<clinit>(Android10Platform.kt:65)
        at okhttp3.internal.platform.Platform$Companion.findPlatform(Platform.kt:206)
        at okhttp3.internal.platform.Platform$Companion.access$findPlatform(Platform.kt:169)
        at okhttp3.internal.platform.Platform.<clinit>(Platform.kt:170)
        at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:224)
        at okhttp3.OkHttpClient$Builder.build(OkHttpClient.kt:1025)
```

And I localized this as the dependency that bumped my transitive dependency on okttp up to 4 from `./gradlew :app:dependencies` - relevant chunk

```
+--- project :notifee_react-native
|    +--- io.jsonwebtoken:jjwt-api:0.10.7
|    +--- com.facebook.react:react-native:+ -> 0.62.2 (*)
|    +--- com.squareup.okhttp3:okhttp-bom:4.4.1
|    |    +--- com.squareup.okhttp3:okhttp:4.4.1 (c)
|    |    \--- com.squareup.okhttp3:okhttp-urlconnection:4.4.1 (c)

```

**Comment by mikehardy** [comment]
@helenaford confirmed release 0.11.1 works on Android 4.x with a real device test, thanks!

**Comment by Salakar** [comment]
Thanks for confirming!
